apiVersion: networking.k8s.io/v1 #networking.k8s.io/v1beta1  ## if you're on kube 1.19 plus this is no longer beta
kind: Ingress
metadata:
  name: web-app-ingress
spec:
  rules:
  - host: api.sa.info
    http:
      paths:
      - path: /sentiment
        pathType: Prefix
        backend:
          service:
            name: sa-web-app-lb
            port:
              number: 80
      - path: /testHealth
        pathType: Prefix
        backend:
          service:
            name: sa-web-app-lb
            port:
              number: 8080
  - host: sa.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sa-frontend-lb
            port:
              number: 80