
apiVersion: v1
kind: Service
metadata:
  name: sa-web-app-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sa-web-app
--- 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-app-ingress
spec:
  rules:
  - host: sa.info
    http:
      paths:
      - path: /sentiment
        pathType: Prefix
        backend:
          serviceName: sa-web-app-lb
          servicePort: 80
      - path: /testHealth
        pathType: Prefix
        backend:
          serviceName: sa-web-app-lb
          servicePort: 8080