
name: MiddleTier

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: 
      - 'sentiment-analysis-webapp/*'
      - '.github/workflows/build-webApp.yml'

jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Build
        run: make build SERVICE=webapp

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Docker Push
        run: make push SERVICE=webapp

