
name: Logic-Backend

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: 
      - 'sentiment-analysis-logic/**'
      - '.github/workflows/build-logic.yml'

jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Build
        run: make build SERVICE=logic

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: make push SERVICE=logic
      - name: Patch Manifest
        if: github.ref == 'refs/heads/main'
        run: make patch_manifest SERVICE=frontend MANIFEST_FILE=resource-manifests/deployment-sa-logic.yaml
      - name: Push Manifest changes
        run: |
          git config --global user.name 'Tom Gray'
          git config --global user.email 'tom-gray@users.noreply.github.com'
          git pull
          git commit -am "Bump image version"
          git push

