
name: Backend

on:
  push:
    branches: [ main ]
    paths: 
      - 'sentiment-analysis-logic/*'
      - '.github/workflows/build-logic.yml'

jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
      - uses: actions/checkout@v2
        run: make build SERVICE=logic

      - name: Docker Push
        run: make push SERVICE=logic

