
name: Python application

on:
  push:
    branches: [ main ]
    paths: 
      - 'sa-logic/*'
      - '.github/workflows/python-app.yml'

jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tom-gray/:latest
          context: .
          file: ./sa-logic/Dockerfile
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

