
name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths: 
      - 'sa-logic/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: sa-logic/sa
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: "${{ secrets.GITHUB_TOKEN }}"


