
name: Release FrontEnd

on:
  workflow_dispatch:
  push:
      paths: 
      - '.github/workflows/release-frontEnd.yml'
      tags:        
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Build
        run: make build SERVICE=frontend

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: make push SERVICE=frontend

      - name: Patch Manifest
        run: | 
          make patch_manifest TAG=${{github.ref_name}} DEPLOYMENT_MANIFEST=resource-manifests/deployment-sa-frontend.yaml SERVICE_MANIFEST=resource-manifests/service-sa-frontend-lb.yaml
      - name: Push Manifest changes
        run: |
          git config --global user.name 'Tom Gray'
          git config --global user.email 'tom-gray@users.noreply.github.com'
          git pull origin main
          git commit -am "release version ${{github.ref_name}}"
          git push origin HEAD:main

